# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  # tag: '$(Build.BuildId)'
  tag: 'latest'
  containerRegistry: 'azureprivaterepo'
  # dockerrepo: 'veracodereg.azurecr.io'
  dockerrepo: 'veraprivate.azurecr.io'

steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: '$(dockerrepo)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'



    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'azureprivaterepo'
    #     repository: 'veraprivate.azurecr.io'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'

    - task: Docker@0
      displayName: 'list contaniers'
      inputs:
        action: 'Run a Docker command'
        customCommand: 'image ls'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'azureprivaterepo'
        command: 'login'
        

    - task: Bash@3
      displayName: tf Scanner
      inputs:
          targetType: inline
          script: |
              pwd
              export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
              export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
              curl -fsS https://tools.veracode.com/veracode-cli/install | sh
              ./veracode scan --type image --source $(dockerrepo):$(tag) --format table 2 >&1 | tee container-scan.json