# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  # tag: '$(Build.BuildId)'
  tag: 'latest'
  containerRegistry: 'azureprivaterepo'
  # dockerrepo: 'veracodereg.azurecr.io'
  dockerrepo: 'veraprivate.azurecr.io'

steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'azureprivaterepo'
        repository: '$(dockerrepo)'
        # command: 'buildAndPush'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'



    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'azureprivaterepo'
    #     repository: 'veraprivate.azurecr.io'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'


    
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'azureprivaterepo'
    #     # command: 'custom'
    #     customCommand: 'login -u acr-ver -p SnuUsxGODYxIvCRAPQ20d91KpA0zH7ZUGwUCRzV9+n+ACRB6AQww veraprivate.azurecr.io'

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
        customCommand: 'login -u acr-ver -p SnuUsxGODYxIvCRAPQ20d91KpA0zH7ZUGwUCRzV9+n+ACRB6AQww veraprivate.azurecr.io'
        
    - task: Docker@0
      displayName: 'list contaniers'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(f0db0ac6-5121-4754-931d-f77a03b34c6f)'
        azureContainerRegistry: '{"loginServer":"veraprivate.azurecr.io", "id" : "/subscriptions/f0db0ac6-5121-4754-931d-f77a03b34c6f/resourceGroups/veracode/providers/Microsoft.ContainerRegistry/registries/veraprivate"}'
        action: 'Run a Docker command'
        customCommand: 'image ls'

    - task: Bash@3
      displayName: tf Scanner
      inputs:
          targetType: inline
          script: |
              pwd
              export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
              export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
              curl -fsS https://tools.veracode.com/veracode-cli/install | sh
              ./veracode scan --type image --source $(dockerrepo):$(tag) --format table 2 >&1 | tee container-scan.json