#This pipeline will install source clear and scan the repo
#Vulnerability details in the Pipeline output
#Results are also available in the Platform based on the Token

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
    targetType: 'inline'
    script: |
          export SRCCLR_API_TOKEN=$(SRCCLR)
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor --recursive
