trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: 'latest'
  containerRegistry: 'azureprivaterepo'
  dockerrepo: 'veracodereg.azurecr.io'

steps:
  - task: Bash@3
    displayName: tf Scanner
    inputs:
      targetType: inline
      script: |
        pwd
        export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
        export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        ./veracode scan --type image --source alpine:latest --format json 2 >&1 | tee container-scan-docker.json

  - task: Bash@3
    displayName: Parse Veracode JSON Results
    inputs:
      targetType: inline
      script: |
        # Parse the JSON and check for the ignored vulnerability
        result=$(jq -r '.["policy-results"][] | select(.type == "Docker" and .message == "Ensure COPY is used instead of ADD in Dockerfile (Not Scored) level 1")' container-scan-docker.json)
        
        # If the vulnerability is found, ignore it
        if [ -z "$result" ]; then
          echo "No non-ignored vulnerabilities found. Policy passed."
          exit 0
        else
          echo "Policy failed due to non-ignored vulnerabilities."
          exit 1
        fi

      # ./veracode scan --type image --source $(dockerrepo):$(tag) --format table 2 >&1 | tee container-scan-docker.json
