# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    - task: Docker@0
      displayName: 'list contaniers'
      inputs:
        action: 'Run a Docker command'
        customCommand: 'image ls'

    - task: Bash@3
      displayName: tf Scanner
      inputs:
          targetType: inline
          script: |
              pwd
              export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
              export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
              curl -fsS https://tools.veracode.com/veracode-cli/install | sh
              ./veracode scan --type image --source '$(Build.SourcesDirectory)/Dockerfile:latest' --format table 2 >&1 | tee container-scan.json
